### ISSUE TITLE
K kam garxa

### ISSUE THREAD

**Issue by meprazhant** [ABChapagain/SHAREPOST-MERN#1]
Yesko main kam chai K?
vercel ma error aairaxa

**Comment by ABChapagain** [comment]
Just title ra description post garna milne ho (so called social media app😂)
Authentication and authorization sikeko bela banako theye.

**Comment by ABChapagain** [comment]
Aba try gara ta ghari ghari aafai error aauxa vercel ma

**Comment by meprazhant** [comment]
ahha ayena. Same error dekhairaxa

**Comment by ABChapagain** [comment]
haha taitt arkai url raixa ni ta🤣
try this https://sharepost.vercel.app/
